name: Split and Deploy to Drupal

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'

      - name: Run Splitter Script
        run: node splitter.js

      - name: Deploy to Drupal Server
        env:
          SSH_KEY: ${{ secrets.SFTP_SSH_KEY }}
          HOST: ${{ secrets.SFTP_SERVER }}
          USER: ${{ secrets.SFTP_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Using relative path from home directory (safer on Cloudways)
          # Removed the trailing slash to prevent mkdir conflicts
          scp -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa dist/* "$USER"@"$HOST":public_html/web/themes/avicenna/dist/
          
          rm ~/.ssh/id_rsa
